# Generated by Django 5.2.9 on 2026-02-14 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_event_managers_event_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-updated_at"]},
        ),
    ]
