# Generated by Django 5.2.9 on 2026-03-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_alter_event_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="display",
            field=models.BooleanField(default=True, verbose_name="Display"),
        ),
        migrations.AddField(
            model_name="event",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Order"),
        ),
    ]
