# Generated by Django 6.0 on 2025-12-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technology_stack', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects_image/')),
                ('link', models.URLField(blank=True, null=True)),
                ('members_info', models.CharField(max_length=200)),
            ],
        ),
    ]
