# Generated by Django 5.2.9 on 2026-01-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_home', models.BooleanField(default=True)),
                ('show_resource', models.BooleanField(default=True)),
                ('show_event', models.BooleanField(default=True)),
                ('show_announcement', models.BooleanField(default=True)),
            ],
        ),
    ]
