# Generated by Django 5.2.9 on 2026-01-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagevisibility",
            name="show_announcement",
        ),
        migrations.RemoveField(
            model_name="pagevisibility",
            name="show_event",
        ),
        migrations.RemoveField(
            model_name="pagevisibility",
            name="show_home",
        ),
        migrations.RemoveField(
            model_name="pagevisibility",
            name="show_resource",
        ),
        migrations.AddField(
            model_name="pagevisibility",
            name="show_about",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pagevisibility",
            name="show_events",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pagevisibility",
            name="show_footer",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pagevisibility",
            name="show_hero",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pagevisibility",
            name="show_projects",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pagevisibility",
            name="show_resources",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pagevisibility",
            name="show_upcoming",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pagevisibility",
            name="show_whatwedo",
            field=models.BooleanField(default=True),
        ),
    ]
