# Generated by Django 5.2.9 on 2026-02-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_whatwedo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisibility',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/banner/', verbose_name='Banner Image'),
        ),
    ]
