# Generated by Django 5.2.9 on 2026-02-14 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0006_alter_pagevisibility_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pagevisibility",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="whatwedo",
            options={"ordering": ["-updated_at"]},
        ),
    ]
