# Generated by Django 5.2.9 on 2026-02-15 13:46

import django.db.models.manager
from django.db import migrations, models


def create_default_values(apps, schema_editor):
    PageSettings = apps.get_model("pages", "PageSettings")
    AboutUs = apps.get_model("pages", "AboutUs")
    PageSettings.objects_all.create()
    AboutUs.objects_all.create()


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0007_alter_pagevisibility_options_alter_whatwedo_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("caption", models.TextField(verbose_name="Caption")),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="pages/about/main/",
                        verbose_name="Main Image",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "location",
                    models.TextField(blank=True, null=True, verbose_name="Location"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Contact Email",
                    ),
                ),
                (
                    "contact_phone",
                    models.TextField(
                        blank=True, null=True, verbose_name="Contact Phone Nos"
                    ),
                ),
                (
                    "contact_facebook",
                    models.TextField(
                        blank=True, null=True, verbose_name="Contact Facebook page"
                    ),
                ),
                (
                    "contact_twitter",
                    models.TextField(
                        blank=True, null=True, verbose_name="Contact Twitter page"
                    ),
                ),
                (
                    "contact_reddit",
                    models.TextField(
                        blank=True, null=True, verbose_name="Contact Reddit page"
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "abstract": False,
            },
            managers=[
                ("objects_all", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="PageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org_name",
                    models.TextField(default="Club", verbose_name="Organization Name"),
                ),
                (
                    "page_icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="pages/icon/",
                        verbose_name="Page Icon",
                    ),
                ),
                ("show_banner", models.BooleanField(default=True)),
                ("show_about", models.BooleanField(default=True)),
                ("show_whatwedo", models.BooleanField(default=True)),
                ("show_upcoming", models.BooleanField(default=True)),
                ("show_projects", models.BooleanField(default=True)),
                ("show_resources", models.BooleanField(default=True)),
                ("show_events", models.BooleanField(default=True)),
                ("show_footer", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-updated_at"],
                "abstract": False,
            },
            managers=[
                ("objects_all", django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name="PageVisibility",
        ),
        migrations.RunPython(create_default_values),
    ]
