# Generated by Django 5.2.9 on 2026-01-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
