# Generated by Django 5.2.9 on 2026-01-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0003_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('semester', models.CharField()),
                ('phone', models.CharField(max_length=15)),
                ('faculty', models.CharField(choices=[('CSIT', 'BSc CSIT'), ('BCA', 'BCA'), ('BBS', 'BBS'), ('BBM', 'BBM'), ('MBA', 'MBA')], max_length=10)),
                ('interested_topics', models.TextField(help_text='Comma separated topics')),
                ('join_date', models.DateTimeField()),
            ],
        ),
    ]
