# Generated by Django 5.2.9 on 2026-01-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_member_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_deactive',
            field=models.BooleanField(default=True),
        ),
    ]
