# Generated by Django 5.2.9 on 2026-01-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_member_is_deactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='semester',
        ),
        migrations.AddField(
            model_name='member',
            name='batch',
            field=models.CharField(default='2025', max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='faculty',
            field=models.CharField(choices=[('CSIT', 'BSc CSIT'), ('BCA', 'BCA'), ('BBS', 'BBS'), ('BBM', 'BBM'), ('MBA', 'MBA'), ('BIT', 'BIT')], max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_deactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
