# Generated by Django 5.2.9 on 2026-01-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='batch',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, choices=[('CSIT', 'BSc CSIT'), ('BCA', 'BCA'), ('BBS', 'BBS'), ('BBM', 'BBM'), ('MBA', 'MBA'), ('BIT', 'BIT')], max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='interested_topics',
            field=models.TextField(blank=True, help_text='Comma separated topics'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
