# Generated by Django 5.2.9 on 2026-02-13 06:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_batch_user_faculty_user_interested_topics_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="batch",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2068", "2068"),
                    ("2069", "2069"),
                    ("2070", "2070"),
                    ("2071", "2071"),
                    ("2072", "2072"),
                    ("2073", "2073"),
                    ("2074", "2074"),
                    ("2075", "2075"),
                    ("2076", "2076"),
                    ("2077", "2077"),
                    ("2078", "2078"),
                    ("2079", "2079"),
                    ("2080", "2080"),
                    ("2081", "2081"),
                    ("2082", "2082"),
                    ("2083", "2083"),
                ],
                max_length=10,
            ),
        ),
    ]
