# Generated by Django 5.2.9 on 2026-02-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_user_created_at_user_deleted_at_user_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
