# Generated by Django 5.2.9 on 2026-02-16 02:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_remove_user_username_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
