# Generated by Django 5.2.9 on 2026-02-14 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0005_alter_resource_managers_resource_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resource",
            options={"ordering": ["-updated_at"]},
        ),
    ]
