# Generated by Django 5.2.9 on 2026-02-14 11:11

import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.TextField(verbose_name="Session Title")),
                ("date", models.DateField(verbose_name="Session Date")),
                (
                    "description",
                    models.TextField(
                        verbose_name="Session Description", blank=True, null=True
                    ),
                ),
                (
                    "attendees",
                    models.ManyToManyField(
                        related_name="attended_sessions", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "abstract": False,
            },
            managers=[
                ("objects_all", django.db.models.manager.Manager()),
            ],
        ),
    ]
